export const ALGORITHM='X25519-HKDF-SHA256-AES256GCM-Ed25519-v1';
const enc=new TextEncoder();
export const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
export const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const join=(...xs)=>{const a=new Uint8Array(xs.reduce((n,x)=>n+x.length,0));let i=0;for(const x of xs){a.set(x,i);i+=x.length;}return a;};
const uuid=s=>Uint8Array.from(s.replaceAll('-','').match(/../g),x=>parseInt(x,16));
export async function fingerprint(publicKey,signingKey){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',join(unb64(publicKey),unb64(signingKey)))),x=>x.toString(16).padStart(2,'0')).join('');}
export async function generateIdentity(){const encryption=await crypto.subtle.generateKey('X25519',true,['deriveBits']);const signing=await crypto.subtle.generateKey('Ed25519',true,['sign','verify']);return {encryption,signing,public_key:b64(await crypto.subtle.exportKey('raw',encryption.publicKey)),signing_public_key:b64(await crypto.subtle.exportKey('raw',signing.publicKey))};}
async function vaultKey(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:600000},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function protect(identity,password){const salt=crypto.getRandomValues(new Uint8Array(16)),nonce=crypto.getRandomValues(new Uint8Array(12));const data=enc.encode(JSON.stringify({encryption:b64(await crypto.subtle.exportKey('pkcs8',identity.encryption.privateKey)),signing:b64(await crypto.subtle.exportKey('pkcs8',identity.signing.privateKey)),public_key:identity.public_key,signing_public_key:identity.signing_public_key}));return {version:1,salt:b64(salt),nonce:b64(nonce),data:b64(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:enc.encode('cypherchat-browser-v1')},await vaultKey(password,salt),data))};}
export async function unlock(blob,password){if(blob.version!==1)throw Error('Formato de cofre incompatível');const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(blob.nonce),additionalData:enc.encode('cypherchat-browser-v1')},await vaultKey(password,unb64(blob.salt)),unb64(blob.data));const data=JSON.parse(new TextDecoder().decode(raw));return {...data,encryption:{privateKey:await crypto.subtle.importKey('pkcs8',unb64(data.encryption),'X25519',true,['deriveBits'])},signing:{privateKey:await crypto.subtle.importKey('pkcs8',unb64(data.signing),'Ed25519',true,['sign'])}};}
export function signedBytes(e){return enc.encode(JSON.stringify(Object.fromEntries(['algorithm','ciphertext','ephemeral_public_key','nonce','recipient_id','sender_id'].map(k=>[k,e[k]]))));}
async function derive(privateKey,publicKey,nonce,sender,recipient){const secret=await crypto.subtle.deriveBits({name:'X25519',public:publicKey},privateKey,256);const material=await crypto.subtle.importKey('raw',secret,'HKDF',false,['deriveKey']);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt:nonce,info:join(enc.encode('cypherchat-v1'),uuid(sender),uuid(recipient))},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function encrypt(identity,contact,sender,text){const ephemeral=await crypto.subtle.generateKey('X25519',true,['deriveBits']);const publicKey=await crypto.subtle.importKey('raw',unb64(contact.public_key),'X25519',false,[]);const nonce=crypto.getRandomValues(new Uint8Array(12));const key=await derive(ephemeral.privateKey,publicKey,nonce,sender,contact.id);const e={algorithm:ALGORITHM,sender_id:sender,recipient_id:contact.id,ephemeral_public_key:b64(await crypto.subtle.exportKey('raw',ephemeral.publicKey)),nonce:b64(nonce),ciphertext:b64(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:join(uuid(sender),uuid(contact.id))},key,enc.encode(text)))};e.signature=b64(await crypto.subtle.sign('Ed25519',identity.signing.privateKey,signedBytes(e)));return e;}
export async function decrypt(identity,contact,e){if(e.algorithm!==ALGORITHM)throw Error('Protocolo incompatível');const signing=await crypto.subtle.importKey('raw',unb64(contact.signing_public_key),'Ed25519',false,['verify']);if(!await crypto.subtle.verify('Ed25519',signing,unb64(e.signature),signedBytes(e)))throw Error('Assinatura inválida');const publicKey=await crypto.subtle.importKey('raw',unb64(e.ephemeral_public_key),'X25519',false,[]);const key=await derive(identity.encryption.privateKey,publicKey,unb64(e.nonce),e.sender_id,e.recipient_id);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(e.nonce),additionalData:join(uuid(e.sender_id),uuid(e.recipient_id))},key,unb64(e.ciphertext)));}
